server:
  port: 8080 #端口号
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/smp_demo01?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  thymeleaf:
    cache: true #开启模板缓存
    check-template: true #
    check-template-location: true #检查模板位置是否正确
    content-type: text/html
    enabled: true #开启mvc解析器
    encoding: UTF-8 #编码
    mode: HTML5
    prefix: classpath:/templates/ #前缀
    suffix: .html #后缀

mybatis:
  type-aliases-package: com.smp.smp_demo02.domain
  mapper-locations: classpath:com.smp.smp_demo02.dao/*.xml
  #使用注解在启动类上面配置 @MapperScan("com.smp.smp_demo02.dao")//存放接口
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis日志

pagehelper:
  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
